# SMU BOSS Bidding Data Quality check

## Purpose
- To prepare ingestion of data into AfterClass.
- Upon combining the scraped data into a CSV file, we noticed that there were some data quality issues. This IPYNB file is to find potential data quality issues and to find ways to mitigate it.

## Identified issues
- Instructors having multi-valued attributes.
- Class1_day having multi-valued attributes.
- Term has different naming convetions whereas .xls downloaded only has one naming convention

In [73]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [74]:
# load the dataset
data = pd.read_csv('transformed_data_w_timings_v3.csv', dtype={'CatalogueNo': str})

C:\Users\tanzh\AppData\Local\Temp\ipykernel_5348\3148326935.py:2: DtypeWarning: Columns (0,15,16,17) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv('transformed_data_w_timings_v3.csv', dtype={'CatalogueNo': str})


In [75]:
data.head()

Term                       Description Section  Vacancy  \
0    2  Financial Reporting and Analysis      G3       42   
1    2                         Valuation      G1       42   
2    2                         Valuation      G2       42   
3    2    Auditing for the Public Sector      G1       42   
4    2          Public Relations Writing      G1       45   

   Before Process Vacancy  Median Bid  Min Bid           Instructor  \
0                       3       25.00    25.00         GOH BENG WEE   
1                       9       10.09    10.09       CHENG NAM SANG   
2                      12       10.03    10.00       CHENG NAM SANG   
3                       7       25.00    25.00         LIM SOO PING   
4                      10       10.00    10.00  YASMIN HANNAH RAMLE   

  Grading Basis class1_day  ... exam_startdate exam_day exam_starttime    AY  \
0        Graded        Wed  ...    20-Apr-2022      Wed          08:30  2021   
1        Graded        Mon  ...    27-Apr-2022      Wed          08:30  2021   
2        Graded        Mon  ...    27-Apr-2022      Wed          08:30  2021   
3        Graded        Thu  ...    27-Apr-2022      Wed          13:00  2021   
4        Graded        Thu  ...            NaN      NaN            NaN  2021   

  Incoming Freshman Incoming Exchange Round Window SubjectArea CatalogueNo  
0                no                no    2A      3        ACCT         224  
1                no                no    2A      3        ACCT         336  
2                no                no    2A      3        ACCT         336  
3                no                no    2A      3        ACCT         409  
4                no                no    2A      3        COMM         225  

[5 rows x 28 columns]

In [76]:
data.describe(include='all')

Term               Description Section       Vacancy  \
count   35734                     35734   35734  35734.000000   
unique      5                       667      45           NaN   
top         2  Management Communication      G1           NaN   
freq    16437                      1388   14088           NaN   
mean      NaN                       NaN     NaN     43.333156   
std       NaN                       NaN     NaN      5.700971   
min       NaN                       NaN     NaN      1.000000   
25%       NaN                       NaN     NaN     45.000000   
50%       NaN                       NaN     NaN     45.000000   
75%       NaN                       NaN     NaN     45.000000   
max       NaN                       NaN     NaN     80.000000   

        Before Process Vacancy    Median Bid       Min Bid        Instructor  \
count             35734.000000  35734.000000  35734.000000             35734   
unique                     NaN           NaN           NaN               929   
top                        NaN           NaN           NaN  Not Assigned Yet   
freq                       NaN           NaN           NaN               509   
mean                 12.125259     27.409722     22.706312               NaN   
std                  12.451885     16.860290     15.130064               NaN   
min                   0.000000     10.000000     10.000000               NaN   
25%                   2.000000     15.092500     10.300000               NaN   
50%                   7.000000     24.000000     17.890000               NaN   
75%                  19.000000     35.000000     30.000000               NaN   
max                  80.000000    300.000000    261.000000               NaN   

       Grading Basis class1_day  ... exam_startdate exam_day exam_starttime  \
count          30909      30531  ...          22456    22456          22456   
unique             2          7  ...             82        6              3   
top           Graded        Tue  ...    25-Nov-2022      Fri          08:30   
freq           30699       6955  ...            471     4731          11331   
mean             NaN        NaN  ...            NaN      NaN            NaN   
std              NaN        NaN  ...            NaN      NaN            NaN   
min              NaN        NaN  ...            NaN      NaN            NaN   
25%              NaN        NaN  ...            NaN      NaN            NaN   
50%              NaN        NaN  ...            NaN      NaN            NaN   
75%              NaN        NaN  ...            NaN      NaN            NaN   
max              NaN        NaN  ...            NaN      NaN            NaN   

                  AY Incoming Freshman Incoming Exchange  Round       Window  \
count   35734.000000             35734             35734  35734  35734.00000   
unique           NaN                 2                 2      6          NaN   
top              NaN                no                no      1          NaN   
freq             NaN             34579             31787  10185          NaN   
mean     2022.609811               NaN               NaN    NaN      1.51763   
std         1.010684               NaN               NaN    NaN      0.65875   
min      2021.000000               NaN               NaN    NaN      1.00000   
25%      2022.000000               NaN               NaN    NaN      1.00000   
50%      2023.000000               NaN               NaN    NaN      1.00000   
75%      2023.000000               NaN               NaN    NaN      2.00000   
max      2024.000000               NaN               NaN    NaN      5.00000   

       SubjectArea CatalogueNo  
count        35734       35734  
unique          55         373  
top            COR         101  
freq          5266        2671  
mean           NaN         NaN  
std            NaN         NaN  
min            NaN         NaN  
25%            NaN         NaN  
50%            NaN         NaN  
75%            NaN         

In [77]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35734 entries, 0 to 35733
Data columns (total 28 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   Term                    35734 non-null  object 
 1   Description             35734 non-null  object 
 2   Section                 35734 non-null  object 
 3   Vacancy                 35734 non-null  int64  
 4   Before Process Vacancy  35734 non-null  int64  
 5   Median Bid              35734 non-null  float64
 6   Min Bid                 35734 non-null  float64
 7   Instructor              35734 non-null  object 
 8   Grading Basis           30909 non-null  object 
 9   class1_day              30531 non-null  object 
 10  class1_starttime        30370 non-null  object 
 11  class1_venue            30336 non-null  object 
 12  class2_day              880 non-null    object 
 13  class2_starttime        880 non-null    object 
 14  class2_venue            880 non-null  

In [78]:
data.isnull().sum()

Term                          0
Description                   0
Section                       0
Vacancy                       0
Before Process Vacancy        0
Median Bid                    0
Min Bid                       0
Instructor                    0
Grading Basis              4825
class1_day                 5203
class1_starttime           5364
class1_venue               5398
class2_day                34854
class2_starttime          34854
class2_venue              34854
class3_day                35677
class3_starttime          35677
class3_venue              35677
exam_startdate            13278
exam_day                  13278
exam_starttime            13278
AY                            0
Incoming Freshman             0
Incoming Exchange             0
Round                         0
Window                        0
SubjectArea                   0
CatalogueNo                   0
dtype: int64

In [79]:
# Check for duplicates
data.duplicated().sum()

np.int64(0)

## ISSUE: Investigate missing grading basis

In [80]:
data['Grading Basis'].value_counts()

Grading Basis
Graded       30699
Pass/Fail      210
Name: count, dtype: int64

In [81]:
missing_grading_basis_data = data[data['Grading Basis'].isna()]
missing_grading_basis_data.head(10)

Term                                        Description Section  Vacancy  \
6      2                           Management Communication      G8       30   
7      2                                           Japanese      G3       45   
8      2                   Business, Government and Society      G3       45   
45     2                           Management Communication     G19       30   
46     2                                           Japanese      G2       45   
47     2               Constitutions, Cultures, and Context      G1       38   
48     2  Jurisprudence: Modern and Critical Theories of...      G1       38   
49     2                   Business, Government and Society     G11       45   
116    2                           Management Communication     G21       30   
117    2                           Management Communication     G30       30   

     Before Process Vacancy  Median Bid  Min Bid            Instructor  \
6                         3       35.00    35.00          CHAN BOH YEE   
7                         2       26.45    26.44  AKIKO ITO, AKIKO ITO   
8                         5       25.00    25.00          CHAN KAY MIN   
45                        3       10.00    10.00             LINDY ONG   
46                        1       10.01    10.01  AKIKO ITO, AKIKO ITO   
47                        1       21.67    21.67     MAARTJE DE VISSER   
48                        8       17.17    17.17          TAN SEOW HON   
49                        2       10.03    10.03   GILBERT TAN YIP WEI   
116                       1       12.77    12.77             LINDY ONG   
117                       1       10.00    10.00        VANDANA ADVANI   

    Grading Basis class1_day  ... exam_startdate exam_day exam_starttime  \
6             NaN        NaN  ...            NaN      NaN            NaN   
7             NaN        NaN  ...            NaN      NaN            NaN   
8             NaN        NaN  ...            NaN      NaN            NaN   
45            NaN        NaN  ...            NaN      NaN            NaN   
46            NaN        NaN  ...            NaN      NaN            NaN   
47            NaN        NaN  ...            NaN      NaN            NaN   
48            NaN        NaN  ...            NaN      NaN            NaN   
49            NaN        NaN  ...            NaN      NaN            NaN   
116           NaN        NaN  ...            NaN      NaN            NaN   
117           NaN        NaN  ...            NaN      NaN            NaN   

       AY Incoming Freshman Incoming Exchange Round Window SubjectArea  \
6    2021                no                no    2A      3    COR-COMM   
7    2021                no                no    2A      3    COR-JPAN   
8    2021                no                no    2A      3    COR-MGMT   
45   2021                no                no    2A      2    COR-COMM   
46   2021                no                no    2A      2    COR-JPAN   
47   2021                no                no    2A      2     COR-LAW   
48   2021                no                no    2A      2     COR-LAW   
49   2021                no                no    2A      2    COR-MGMT   
116  2021                no                no    2A      1    COR-COMM   
117  2021                no                no    2A      1    COR-COMM   

    CatalogueNo  
6          1304  
7          2401  
8          1302  
45         1304  
46         2401  
47         2610  
48         2612  
49         1302  
116        1304  
117        1304  

[10 rows x 28 columns]

In [82]:
missing_grading_basis_data.describe(include='all').T

count unique                       top  freq  \
Term                      4825      5                         1  2315   
Description               4825     72  Management Communication  1388   
Section                   4825     42                        G1  1270   
Vacancy                 4825.0    NaN                       NaN   NaN   
Before Process Vacancy  4825.0    NaN                       NaN   NaN   
Median Bid              4825.0    NaN                       NaN   NaN   
Min Bid                 4825.0    NaN                       NaN   NaN   
Instructor                4825    120               ROSIE CHING   170   
Grading Basis                0      0                       NaN   NaN   
class1_day                   0      0                       NaN   NaN   
class1_starttime             0      0                       NaN   NaN   
class1_venue                 0      0                       NaN   NaN   
class2_day                   0      0                       NaN   NaN   
class2_starttime             0      0                       NaN   NaN   
class2_venue                 0      0                       NaN   NaN   
class3_day                   0      0                       NaN   NaN   
class3_starttime             0      0                       NaN   NaN   
class3_venue                 0      0                       NaN   NaN   
exam_startdate               0      0                       NaN   NaN   
exam_day                     0      0                       NaN   NaN   
exam_starttime               0      0                       NaN   NaN   
AY                      4825.0    NaN                       NaN   NaN   
Incoming Freshman         4825      2                        no  4283   
Incoming Exchange         4825      2                        no  4508   
Round                     4825      6                         1  1754   
Window                  4825.0    NaN                       NaN   NaN   
SubjectArea               4825     25                  COR-COMM  1548   
CatalogueNo               4825     70                      1304  1388   

                               mean        std     min     25%     50%  \
Term                            NaN        NaN     NaN     NaN     NaN   
Description                     NaN        NaN     NaN     NaN     NaN   
Section                         NaN        NaN     NaN     NaN     NaN   
Vacancy                   39.786736   7.707542     4.0    30.0    45.0   
Before Process Vacancy    11.005389  11.243239     0.0     2.0     6.0   
Median Bid                28.591422  15.236722    10.0    17.9   25.69   
Min Bid                   23.923685  14.195842    10.0    12.0    20.0   
Instructor                      NaN        NaN     NaN     NaN     NaN   
Grading Basis                   NaN        NaN     NaN     NaN     NaN   
class1_day                      NaN        NaN     NaN     NaN     NaN   
class1_starttime                NaN        NaN     NaN     NaN     NaN   
class1_venue                    NaN        NaN     NaN     NaN     NaN   
class2_day                      NaN        NaN     NaN     NaN     NaN   
class2_starttime                NaN        NaN     NaN     NaN     NaN   
class2_venue                    NaN        NaN     NaN     NaN     NaN   
class3_day                      NaN        NaN     NaN     NaN     NaN   
class3_starttime                NaN        NaN     NaN     NaN     NaN   
class3_venue                    NaN        NaN     NaN     NaN     NaN   
exam_startdate                  NaN        NaN     NaN     NaN     NaN   
exam_day                        NaN        NaN     NaN     NaN     NaN   
exam_starttime                  NaN        NaN     NaN     NaN     NaN   
AY                      2022.752953   1.002435  2021.0  2022.0  2023.0   
Incoming Freshman               NaN        NaN     NaN     NaN     NaN   
Incoming Exchange               NaN        NaN     NaN     NaN     NaN   
Round                           NaN        NaN     NaN   

In [83]:
missing_grading_basis_data[missing_grading_basis_data['Description']=='Management Communication'].head(1).T

6
Term                                           2
Description             Management Communication
Section                                       G8
Vacancy                                       30
Before Process Vacancy                         3
Median Bid                                  35.0
Min Bid                                     35.0
Instructor                          CHAN BOH YEE
Grading Basis                                NaN
class1_day                                   NaN
class1_starttime                             NaN
class1_venue                                 NaN
class2_day                                   NaN
class2_starttime                             NaN
class2_venue                                 NaN
class3_day                                   NaN
class3_starttime                             NaN
class3_venue                                 NaN
exam_startdate                               NaN
exam_day                                     NaN
exam_starttime                               NaN
AY                                          2021
Incoming Freshman                             no
Incoming Exchange                             no
Round                                         2A
Window                                         3
SubjectArea                             COR-COMM
CatalogueNo                                 1304

## ROOT CAUSE: Scraping logic not waiting for website to be fully loaded, skipping it
Investigating into row 6 more, I found the class at https://boss.intranet.smu.edu.sg/ClassDetails.aspx?SelectedClassNumber=1609&SelectedAcadTerm=2120&SelectedAcadCareer=UGRD, which was not recorded in the csv. 

From this, I have identified that the scraping code didn't wait for page elements to load completely before attempting to extract data, thus causing the code to skip the page.

## FIX: Wait until page is healthy before scraping
To fix this, the code will have to `WebDriverWait.until()` function from selenium to wait for the page to load before extracting data.

---

## ISSUE: Missing class1_day

In [84]:
missing_class1_day_data = data[data['Grading Basis'].notna() & data['class1_day'].isna()]
missing_class1_day_data.head(10)

Term                                        Description Section  Vacancy  \
1732    2                      Virtual Business Professional      G1       25   
2218    2                      Virtual Business Professional      G1       25   
2483    2                            Health Economics(SMU-X)      G3       45   
2617    2  The Singapore International Arbitration Centre...      G1       38   
2675    2                  Entrepreneurship Practicum(SMU-X)      G2       45   
2723    2         Legal Environment and Employment Relations      G1       45   
2739    2       Operations Strategy: Principles and Practice      G1       45   
2783    2                      Virtual Business Professional      G1       25   
2814    2                     Accounting Information Systems      G4       45   
2834    2                      Advanced Financial Accounting      G2       45   

      Before Process Vacancy  Median Bid  Min Bid        Instructor  \
1732                      16       25.00    25.00  Not Assigned Yet   
2218                      15       12.28    12.28  Not Assigned Yet   
2483                      38       20.00    20.00  Not Assigned Yet   
2617                      32       11.01    11.01  Not Assigned Yet   
2675                      38       12.01    12.01  Not Assigned Yet   
2723                      31       13.98    11.74  Not Assigned Yet   
2739                      26       15.85    11.66  Not Assigned Yet   
2783                      15       11.20    10.00  Not Assigned Yet   
2814                      32       10.89    10.00  Not Assigned Yet   
2834                      27       20.00    20.00  Not Assigned Yet   

     Grading Basis class1_day  ... exam_startdate exam_day exam_starttime  \
1732        Graded        NaN  ...            NaN      NaN            NaN   
2218        Graded        NaN  ...            NaN      NaN            NaN   
2483        Graded        NaN  ...            NaN      NaN            NaN   
2617        Graded        NaN  ...            NaN      NaN            NaN   
2675        Graded        NaN  ...            NaN      NaN            NaN   
2723        Graded        NaN  ...            NaN      NaN            NaN   
2739        Graded        NaN  ...            NaN      NaN            NaN   
2783        Graded        NaN  ...            NaN      NaN            NaN   
2814        Graded        NaN  ...            NaN      NaN            NaN   
2834        Graded        NaN  ...            NaN      NaN            NaN   

        AY Incoming Freshman Incoming Exchange Round Window SubjectArea  \
1732  2021                no                no    1B      2        WRIT   
2218  2021                no                no    1B      1        WRIT   
2483  2021                no                no    1A      2        ECON   
2617  2021                no                no    1A      2         LAW   
2675  2021                no                no    1A      2        MGMT   
2723  2021                no                no    1A      2        OBHR   
2739  2021                no                no    1A      2        OPIM   
2783  2021                no                no    1A      2        WRIT   
2814  2021                no                no    1A      1        ACCT   
2834  2021                no                no    1A      1        ACCT   

     CatalogueNo  
1732         200  
2218         200  
2483         215  
2617        4020  
2675         327  
2723         232  
2739         319  
2783         200  
2814         221  
2834         335  

[10 rows x 28 columns]

In [85]:
missing_class1_day_data.describe(include='all').T

count unique                               top freq  \
Term                      378      5                                 2  164   
Description               378    107  Computing Technology For Finance   13   
Section                   378     13                                G1  213   
Vacancy                 378.0    NaN                               NaN  NaN   
Before Process Vacancy  378.0    NaN                               NaN  NaN   
Median Bid              378.0    NaN                               NaN  NaN   
Min Bid                 378.0    NaN                               NaN  NaN   
Instructor                378      3                  Not Assigned Yet  370   
Grading Basis             378      2                            Graded  374   
class1_day                  0      0                               NaN  NaN   
class1_starttime            0      0                               NaN  NaN   
class1_venue                0      0                               NaN  NaN   
class2_day                  0      0                               NaN  NaN   
class2_starttime            0      0                               NaN  NaN   
class2_venue                0      0                               NaN  NaN   
class3_day                  0      0                               NaN  NaN   
class3_starttime            0      0                               NaN  NaN   
class3_venue                0      0                               NaN  NaN   
exam_startdate              0      0                               NaN  NaN   
exam_day                    0      0                               NaN  NaN   
exam_starttime              0      0                               NaN  NaN   
AY                      378.0    NaN                               NaN  NaN   
Incoming Freshman         378      1                                no  378   
Incoming Exchange         378      2                                no  376   
Round                     378      4                                 1  202   
Window                  378.0    NaN                               NaN  NaN   
SubjectArea               378     22                              COMM   51   
CatalogueNo               378     83                               205   16   

                               mean        std     min      25%     50%  \
Term                            NaN        NaN     NaN      NaN     NaN   
Description                     NaN        NaN     NaN      NaN     NaN   
Section                         NaN        NaN     NaN      NaN     NaN   
Vacancy                   43.185185   5.658973     7.0     45.0    45.0   
Before Process Vacancy    30.325397   7.695976     0.0     27.0    31.5   
Median Bid                 18.85082  10.678839    10.0  11.8825   15.45   
Min Bid                   13.763492   7.647385    10.0     10.0  10.105   
Instructor                      NaN        NaN     NaN      NaN     NaN   
Grading Basis                   NaN        NaN     NaN      NaN     NaN   
class1_day                      NaN        NaN     NaN      NaN     NaN   
class1_starttime                NaN        NaN     NaN      NaN     NaN   
class1_venue                    NaN        NaN     NaN      NaN     NaN   
class2_day                      NaN        NaN     NaN      NaN     NaN   
class2_starttime                NaN        NaN     NaN      NaN     NaN   
class2_venue                    NaN        NaN     NaN      NaN     NaN   
class3_day                      NaN        NaN     NaN      NaN     NaN   
class3_starttime                NaN        NaN     NaN      NaN     NaN   
class3_venue                    NaN        NaN     NaN      NaN     NaN   
exam_startdate                  NaN        NaN     NaN      NaN     NaN   
exam_day                        NaN        NaN     NaN      NaN     NaN   
exam_starttime                  NaN        NaN     NaN      NaN     NaN   
AY                      2022.574074   1.124157  2021.0   2022.0  2022.0   
Incomin

In [86]:
missing_class1_day_data.head(10).T

1732  \
Term                                                2   
Description             Virtual Business Professional   
Section                                            G1   
Vacancy                                            25   
Before Process Vacancy                             16   
Median Bid                                       25.0   
Min Bid                                          25.0   
Instructor                           Not Assigned Yet   
Grading Basis                                  Graded   
class1_day                                        NaN   
class1_starttime                                  NaN   
class1_venue                                      NaN   
class2_day                                        NaN   
class2_starttime                                  NaN   
class2_venue                                      NaN   
class3_day                                        NaN   
class3_starttime                                  NaN   
class3_venue                                      NaN   
exam_startdate                                    NaN   
exam_day                                          NaN   
exam_starttime                                    NaN   
AY                                               2021   
Incoming Freshman                                  no   
Incoming Exchange                                  no   
Round                                              1B   
Window                                              2   
SubjectArea                                      WRIT   
CatalogueNo                                       200   

                                                 2218  \
Term                                                2   
Description             Virtual Business Professional   
Section                                            G1   
Vacancy                                            25   
Before Process Vacancy                             15   
Median Bid                                      12.28   
Min Bid                                         12.28   
Instructor                           Not Assigned Yet   
Grading Basis                                  Graded   
class1_day                                        NaN   
class1_starttime                                  NaN   
class1_venue                                      NaN   
class2_day                                        NaN   
class2_starttime                                  NaN   
class2_venue                                      NaN   
class3_day                                        NaN   
class3_starttime                                  NaN   
class3_venue                                      NaN   
exam_startdate                                    NaN   
exam_day                                          NaN   
exam_starttime                                    NaN   
AY                                               2021   
Incoming Freshman                                  no   
Incoming Exchange                                  no   
Round                                              1B   
Window                                              1   
SubjectArea                                      WRIT   
CatalogueNo                                       200   

                                           2483  \
Term                                          2   
Description             Health Economics(SMU-X)   
Section                                      G3   
Vacancy                                      45   
Before Process Vacancy                       38   
Median Bid                                 20.0   
Min Bid                                    20.0   
Instructor                     Not Assigned Yet   
Grading Basis                            Graded   
class1_day                                  NaN   
class1_starttime                            NaN   
class1_venue                                NaN   
class2_day                                  NaN   
class2_starttime           

In [87]:
missing_class1_day_data.loc[1732].T

Term                                                  2
Description               Virtual Business Professional
Section                                              G1
Vacancy                                              25
Before Process Vacancy                               16
Median Bid                                         25.0
Min Bid                                            25.0
Instructor                             Not Assigned Yet
Grading Basis                                    Graded
class1_day                                          NaN
class1_starttime                                    NaN
class1_venue                                        NaN
class2_day                                          NaN
class2_starttime                                    NaN
class2_venue                                        NaN
class3_day                                          NaN
class3_starttime                                    NaN
class3_venue                                    

In [88]:
missing_class1_day_data.loc[2814].T

Term                                                   2
Description               Accounting Information Systems
Section                                               G4
Vacancy                                               45
Before Process Vacancy                                32
Median Bid                                         10.89
Min Bid                                             10.0
Instructor                              Not Assigned Yet
Grading Basis                                     Graded
class1_day                                           NaN
class1_starttime                                     NaN
class1_venue                                         NaN
class2_day                                           NaN
class2_starttime                                     NaN
class2_venue                                         NaN
class3_day                                           NaN
class3_starttime                                     NaN
class3_venue                   

## ROOT CAUSE: (1) There is no physical class or (2) Class no longer exists

### SUB-ISSUE 1: There is no physical class
Investigating into row 1732 more, I found the class at https://boss.intranet.smu.edu.sg/ClassDetails.aspx?SelectedClassNumber=2052&SelectedAcadTerm=2120&SelectedAcadCareer=UGRD, was recorded in the csv. 
The class was virtual, so there was no class location.

### SUB-ISSUE 2: Class no longer exists in OverallResults
Investigating into row 2814 more, I found the class at https://boss.intranet.smu.edu.sg/ClassDetails.aspx?SelectedClassNumber=1778&SelectedAcadTerm=2120&SelectedAcadCareer=UGRD, was recorded in the csv. 

Upon looking at https://boss.intranet.smu.edu.sg/OverallResults.aspx, I found that the record did not exist in the Overall Results, likely because it was a class that they decided not to use.

However, it existed in the BOSS results excel table given to us at OASIS.

In [89]:
data.groupby(['Round','Window'])[['Round','Window']].value_counts()

Round  Window
1      1         6524
       2         3357
       3          175
       4          129
1A     1         4822
       2         3577
       3          744
1B     1         2811
       2         2139
1C     1         2264
       2         1083
       3          600
2      1         3177
       2         1782
       3         1145
       4            9
       5            2
2A     1          787
       2          405
       3          202
Name: count, dtype: int64

In [109]:
# Group by class identifiers and count total rows
class_row_counts = (
    data[data['Grading Basis'].notna() & data['class1_day'].isna()]
    .groupby(['CatalogueNo', 'SubjectArea', 'Section', 'AY', 'Term'])
    .size()
    .reset_index(name='num_rows')
)

# Filter if needed
low_activity_classes = class_row_counts[class_row_counts['num_rows'] <= 14]

low_activity_classes = low_activity_classes.sort_values(by='AY', ascending=True)
low_activity_classes.head(10)

CatalogueNo SubjectArea Section    AY Term  num_rows
1          100        IDIS      G2  2021    2         3
13         103        MKTG      G7  2021    2         2
14         103        MKTG      G8  2021    2         3
15         104        MGMT      G2  2021    2         3
12         103        MKTG      G5  2021    2         1
11         103        FNCE      G2  2021    2         3
30         200        WRIT      G1  2021    2         6
26        1305         COR      G9  2021    2         3
25        1305         COR     G15  2021    2         2
61         221        ACCT      G4  2021    2         3

In [110]:
low_activity_classes.count()

CatalogueNo    137
SubjectArea    137
Section        137
AY             137
Term           137
num_rows       137
dtype: int64

In [ ]:
# Define the correct ordering of bidding phases
custom_order = [
    '1-1', '1-2',
    '1A-1', '1A-2',
    '1B-1', '1B-2',
    '2-1', '2-2', '2-3', '2-4', '2-5',
    '2A-1', '2A-2', '2A-3'
]

# Create a combined identifier for round and window
data['bidding_phase'] = data['Round'].astype(str) + '-' + data['Window'].astype(str)

# Convert to ordered categorical to ensure proper sorting
data['bidding_phase'] = pd.Categorical(
    data['bidding_phase'], 
    categories=custom_order, 
    ordered=True
)

# Find the maximum round and window for each class
max_phases = (
    data
    .groupby(['CatalogueNo', 'SubjectArea', 'Section', 'AY', 'Term'])['bidding_phase']
    .max()
    .reset_index()
)

# Define target phase
target_phase = '2A-3'

# Filter classes that didn't reach Round 2A, Window 3
classes_not_reaching_2A_3 = max_phases[max_phases['bidding_phase'] < target_phase]

# Sort and display results
classes_not_reaching_2A_3 = classes_not_reaching_2A_3.sort_values(by='AY', ascending=True)
classes_not_reaching_2A_3.head(10)

CatalogueNo SubjectArea Section    AY Term bidding_phase
3662         213          IS      G9  2023    2          1B-1
2096        1302    COR-MGMT      G9  2021    2           2-2
326          101        FNCE      G9  2023    2           2-1
325          101        FNCE      G9  2023    1           2-3
324          101        FNCE      G9  2022    2          1A-2
323          101        FNCE      G9  2022    1           2-3
322          101        FNCE      G9  2021    2           2-2
3766         215          IS      G9  2021    2          2A-2
3767         215          IS      G9  2022    2           2-3
3768         215          IS      G9  2023    2          1B-1

## FIX: Filter out classes that did not reach Round 2A Window 3
- Upon investigating, not all records in the above code indicate phantom classes. However, investigating MKTG103 in AY2021T2 for G5, G7, G8, it is no longer available in OverallResults.
- The current data omits any records with `Min Bid` == 0, which means that some of the missing `bidding_phase` are not caused by dropped classes, but by lack of active bidders.
- This means that the phantom classes that were cancelled due to lack of venue or instructors did not make it to Round 2A Window 3, making it a suitable filtering option to remove phantom classes.

To fix SUB-ISSUE 2, drop any rows with 0 median/min bid prices, no class1_day, and did not reach Round 2A Window 3.