"""
SafetyFactorProcessor - generates safety factors for bid predictions.
Refactored to pure function pattern with explicit parameters.
"""
from typing import List, Optional
import os
from pathlib import Path

from src.pipeline.dtos.bid_prediction_dto import SafetyFactorDTO
from src.pipeline.safety_factor_calculator import SafetyFactorCalculator


class SafetyFactorProcessor:
    """Generates safety factor multipliers from model validation results."""

    def __init__(
        self,
        expected_acad_term_id: str,
        cache_dir: str = 'db_cache',
        logger: Optional[object] = None
    ):
        self._expected_acad_term_id = expected_acad_term_id
        self._cache_dir = cache_dir
        self._logger = logger

    def _normalize_acad_term_id(self, acad_term_id: str) -> str:
        """Convert dash format (2025-26_T3A) to underscore format (AY202526T3A)."""
        if '-' in acad_term_id and '_' in acad_term_id:
            parts = acad_term_id.split('_')
            years = parts[0].split('-')
            return f"AY{years[0]}{years[1]}{parts[1]}"
        return acad_term_id

    def process(self) -> List['SafetyFactorDTO']:
        """Execute safety factor processing. Returns list of SafetyFactorDTOs."""
        if self._already_exists():
            self._logger.info(f"Safety factors already exist for {self._expected_acad_term_id} - skipping generation")
            return []

        # Convert acad_term_id to underscore format for use in create_safety_factor_table
        normalized_acad_term_id = self._normalize_acad_term_id(self._expected_acad_term_id)

        calculator = SafetyFactorCalculator(self._logger)
        sf_df = calculator.create_safety_factor_table(normalized_acad_term_id)

        if sf_df.empty:
            return []

        safety_factors = []
        for _, row in sf_df.iterrows():
            # Convert from dash format (2025-26_T3A) to underscore format (AY202526T3A)
            acad_term_id = row['acad_term_id']
            if '-' in acad_term_id and '_' in acad_term_id:
                parts = acad_term_id.split('_')
                years = parts[0].split('-')
                acad_term_id = f"AY{years[0]}{years[1]}{parts[1]}"

            sf_dto = SafetyFactorDTO.from_row(
                acad_term_id=acad_term_id,
                prediction_type=row['prediction_type'],
                beats_percentage=int(row['beats_percentage']),
                multiplier=float(row['multiplier']),
                multiplier_type=row['multiplier_type']
            )
            safety_factors.append(sf_dto)

        self._logger.info(f"Generated {len(safety_factors)} safety factor entries")

        # Create cache file to mark safety factors as generated
        self._mark_as_generated()

        return safety_factors

    def _mark_as_generated(self) -> None:
        """Mark safety factors as generated by creating cache file."""
        safety_factor_path = os.path.join(self._cache_dir, 'safety_factors_cache.pkl')
        Path(safety_factor_path).touch()

    def _already_exists(self) -> bool:
        """Check if safety factors cache file exists."""
        safety_factor_path = os.path.join(self._cache_dir, 'safety_factors_cache.pkl')
        return os.path.exists(safety_factor_path)

    