"""
SafetyFactorProcessor - generates safety factors for bid predictions.
Refactored to pure function pattern with explicit parameters.
"""
from typing import List, Optional
import os
from pathlib import Path

from src.config import ACAD_TERM_ID
from src.pipeline.dtos.bid_prediction_dto import SafetyFactorDTO
from src.pipeline.safety_factor_calculator import SafetyFactorCalculator


class SafetyFactorProcessor:
    """Generates safety factor multipliers from model validation results."""

    def __init__(
        self,
        expected_acad_term_id: str,
        cache_dir: str = 'db_cache',
        logger: Optional[object] = None
    ):
        # expected_acad_term_id should already be ACAD_TERM_ID (BOSS format)
        self._expected_acad_term_id = expected_acad_term_id
        self._cache_dir = cache_dir
        self._logger = logger

    def process(self) -> List['SafetyFactorDTO']:
        """Execute safety factor processing. Returns list of SafetyFactorDTOs."""
        if self._already_exists():
            self._logger.info(f"Safety factors already exist for {self._expected_acad_term_id} - skipping generation")
            return []

        # _expected_acad_term_id is already ACAD_TERM_ID (BOSS format)
        calculator = SafetyFactorCalculator(self._logger)
        sf_df = calculator.create_safety_factor_table(self._expected_acad_term_id)

        if sf_df.empty:
            return []

        safety_factors = []
        for _, row in sf_df.iterrows():
            # acad_term_id from create_safety_factor_table should already be in BOSS format
            acad_term_id = row['acad_term_id']

            sf_dto = SafetyFactorDTO.from_row(
                acad_term_id=acad_term_id,
                prediction_type=row['prediction_type'],
                beats_percentage=int(row['beats_percentage']),
                multiplier=float(row['multiplier']),
                multiplier_type=row['multiplier_type']
            )
            safety_factors.append(sf_dto)

        self._logger.info(f"Generated {len(safety_factors)} safety factor entries")

        # Create cache file to mark safety factors as generated
        self._mark_as_generated()

        return safety_factors

    def _mark_as_generated(self) -> None:
        """Mark safety factors as generated by creating cache file."""
        safety_factor_path = os.path.join(self._cache_dir, 'safety_factors_cache.pkl')
        Path(safety_factor_path).touch()

    def _already_exists(self) -> bool:
        """Check if safety factors cache file exists."""
        safety_factor_path = os.path.join(self._cache_dir, 'safety_factors_cache.pkl')
        return os.path.exists(safety_factor_path)

    