"""
Configuration for BidlySMU pipeline.

Load environment variables from .env file.
"""
import json
import os
import re
from datetime import datetime, timedelta, timezone
from typing import Any, Callable, Dict, List, Optional, Tuple

from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()


# ============================================================================
# SUPABASE STORAGE CONFIGURATION (for cloud deployment)
# ============================================================================

SUPABASE_URL = os.getenv('SUPABASE_URL')
SUPABASE_SERVICE_KEY = os.getenv('SUPABASE_SERVICE_KEY')

# Flag to enable Supabase Storage integration (set via environment)
USE_SUPABASE_STORAGE = os.getenv('USE_SUPABASE_STORAGE', 'false').lower() == 'true'


# ============================================================================
# DATABASE CONFIGURATION
# ============================================================================

DB_CONFIG = {
    'host': os.getenv('DB_HOST', 'localhost'),
    'database': os.getenv('DB_NAME', 'postgres'),
    'user': os.getenv('DB_USER', 'postgres'),
    'password': os.getenv('DB_PASSWORD', ''),
    'port': os.getenv('DB_PORT', '5432'),
}


# ============================================================================
# ENVIRONMENT-BASED CONFIGURATION
# ============================================================================

# Academic term ID in BOSS database format (from env)
# Example: AY202526T3A = Academic Year 2025/26, Term 3A
ACAD_TERM_ID = os.getenv('ACAD_TERM_ID', 'AY202526T3A')

# Bidding schedules loaded from JSON file (path from env)
# Format: {"2025-26_T1": [["2025-07-09T14:00:00", "Round 1 Window 1", "R1W1",
#                           "2025-07-07T10:00:00", "2025-07-09T10:00:00"], ...]}
# Each entry: [results_at, title, abbrev, opens_at, closes_at]
# Generated by the Lambda scheduler via BossWindow.to_schedule_entry()
def _load_bidding_schedules() -> Dict[str, List[Tuple[datetime, str, str, datetime, datetime]]]:
    """Load bidding schedules from JSON file specified in env."""
    schedules_path = os.getenv('BIDDING_SCHEDULES_PATH', 'script_input/bidding_schedules.json')

    try:
        with open(schedules_path, 'r') as f:
            raw_schedules = json.load(f)

        # Convert JSON format to Python format with datetime objects
        # Entries may have 3 or 5 elements:
        #   Legacy:   [results_at, title, abbrev]
        #   Extended: [results_at, title, abbrev, opens_at, closes_at]
        schedules = {}
        for term, entries in raw_schedules.items():
            parsed = []
            for entry in entries:
                results_at = datetime.fromisoformat(entry[0])
                title = entry[1]
                abbrev = entry[2]
                opens_at = datetime.fromisoformat(entry[3]) if len(entry) >= 5 and entry[3] else None
                closes_at = datetime.fromisoformat(entry[4]) if len(entry) >= 5 and entry[4] else None
                parsed.append((results_at, title, abbrev, opens_at, closes_at))
            schedules[term] = parsed
        return schedules
    except FileNotFoundError:
        print(f"Warning: BIDDING_SCHEDULES_PATH '{schedules_path}' not found. Using empty schedules.")
        return {}
    except Exception as e:
        print(f"Warning: Error loading bidding schedules: {e}. Using empty schedules.")
        return {}

BIDDING_SCHEDULES = _load_bidding_schedules()


# ============================================================================
# DERIVED VALUES
# ============================================================================

# START_AY_TERM is the dash format used by bidding schedules (e.g., '2025-26_T3A')
# Derived from ACAD_TERM_ID
_START_YEAR = ACAD_TERM_ID[2:6]
_END_YEAR = ACAD_TERM_ID[6:8]
_TERM = ACAD_TERM_ID[8:]
START_AY_TERM = f"{_START_YEAR}-{_END_YEAR}_{_TERM}"

# Term display format mapping for BOSS UI (e.g., 'T3A' -> 'Term 3A')
TERM_DISPLAY_MAP = {
    'T1': 'Term 1',
    'T2': 'Term 2',
    'T3A': 'Term 3A',
    'T3B': 'Term 3B'
}

# Canonical round ordering for sorting bid windows.
# Keys are WITHOUT the "R" prefix (matching parse_bidding_window output).
ROUND_ORDER: Dict[str, int] = {
    '1': 1, '1A': 2, '1B': 3, '1C': 4, '1F': 5, '2': 6, '2A': 7,
}

# Singapore Time (SGT) — UTC+8
# All BOSS bidding windows use SGT wall-clock times.
SGT = timezone(timedelta(hours=8))

def acad_term_id_to_display_format(acad_term_id: str) -> str:
    """
    Convert ACAD_TERM_ID (e.g., 'AY202526T3A') to display format (e.g., '2025-26 Term 3A').

    Usage:
        acad_term_id_to_display_format('AY202526T3A') -> '2025-26 Term 3A'
    """
    if not acad_term_id or len(acad_term_id) < 9:
        return acad_term_id
    start_year = acad_term_id[2:6]
    end_year = acad_term_id[6:8]
    term_code = acad_term_id[8:]
    display_term = TERM_DISPLAY_MAP.get(term_code, term_code)
    return f"{start_year}-{end_year} {display_term}"

# START_AY_TERM_DISPLAY is the BOSS UI format (e.g., '2025-26 Term 3A')
# Used by scrapers to interact with BOSS dropdown selectors
START_AY_TERM_DISPLAY = acad_term_id_to_display_format(ACAD_TERM_ID)

# Results release datetime passed by the Lambda scheduler (single window, current run)
# Format: ISO 8601 with timezone, e.g. "2026-07-04T14:00:00+08:00"
RESULTS_DATETIME = os.getenv('RESULTS_DATETIME')

# Precomputed BOSS URL parameter for current term
# Format: last 2 digits of START year + term digit + subterm code
#   Term 1/2 -> trailing 0: e.g. "2610", "2520"
#   Term 3A  -> trailing 1: e.g. "2531"
#   Term 3B  -> trailing 2: e.g. "2532"
_start_year_2digits = f"{int(ACAD_TERM_ID[2:6]) % 100:02d}"  # "AY202627T1" -> "26"
_term_raw = _TERM[1:] if _TERM.startswith('T') else _TERM
_term_num = _term_raw[0]
if _term_raw.endswith('A'):
    _sub = '1'
elif _term_raw.endswith('B'):
    _sub = '2'
else:
    _sub = '0'
ACAD_TERM_SHORT = f"{_start_year_2digits}{_term_num}{_sub}"  # "2610"

def display_format_to_acad_term_id(display_format: str) -> str:
    """
    Convert display format (e.g., '2025-26 Term 3A') to ACAD_TERM_ID (e.g., 'AY202526T3A').

    Usage:
        display_format_to_acad_term_id('2025-26 Term 3A') -> 'AY202526T3A'
    """
    if not display_format:
        return display_format

    # Pattern: "2025-26 Term 3A" -> extract year, term code
    match = re.match(r'(\d{4})-(\d{2})\s+Term\s+([A-Z0-9]+)', display_format)
    if match:
        start = match.group(1)
        end = match.group(2)
        term_code = match.group(3).upper()  # e.g., '3A', '1', '3B'
        # Add T prefix if not present - '1' -> 'T1', '3A' -> 'T3A'
        if not term_code.startswith('T'):
            term_code = 'T' + term_code
        # Derive from current ACAD_TERM_ID pattern: AY + start + end + term_code
        acad_term_id = f"AY{start}{end}{term_code}"
        return acad_term_id

    # Try dash format "2025-26_T3A"
    match = re.match(r'(\d{4})-(\d{2})_([A-Z0-9]+)', display_format)
    if match:
        start = match.group(1)
        end = match.group(2)
        term_code = match.group(3).upper()
        if not term_code.startswith('T'):
            term_code = 'T' + term_code
        acad_term_id = f"AY{start}{end}{term_code}"
        return acad_term_id

    return display_format


# ============================================================================
# CENTRALIZED TERM & WINDOW FORMATTING HELPERS
# ============================================================================


def dash_format_to_acad_term_id(dash: str) -> str:
    """
    Convert dash format (e.g., '2026-27_T1') to BOSS acad_term_id (e.g., 'AY202627T1').

    Usage:
        dash_format_to_acad_term_id('2026-27_T1') -> 'AY202627T1'
    """
    return "AY" + dash.replace('-', '').replace('_', '')


def acad_term_id_to_dash_format(acad_term_id: str) -> str:
    """
    Convert BOSS acad_term_id (e.g., 'AY202627T1') to dash format (e.g., '2026-27_T1').

    Usage:
        acad_term_id_to_dash_format('AY202627T1') -> '2026-27_T1'
    """
    if not acad_term_id or len(acad_term_id) < 9:
        return acad_term_id
    return f"{acad_term_id[2:6]}-{acad_term_id[6:8]}_{acad_term_id[8:]}"


def abbrev_window_to_full(abbrev: str) -> str:
    """
    Convert abbreviated bid window (e.g., 'R1AW2') to full display format
    (e.g., 'Round 1A Window 2'). Returns input unchanged if no match.

    Usage:
        abbrev_window_to_full('R1AW2') -> 'Round 1A Window 2'
        abbrev_window_to_full('R1FW4') -> 'Round 1F Window 4'
        abbrev_window_to_full('R2W1')  -> 'Round 2 Window 1'
    """
    match = re.match(r'^R(\d+)([A-CF]*?)W(\d+)$', abbrev, re.IGNORECASE)
    if not match:
        return abbrev
    rnd = f"Round {match.group(1)}{match.group(2)}"
    win = f"Window {match.group(3)}"
    return f"{rnd} {win}"


def build_window_abbrev(round_str: str, window_num: int) -> str:
    """
    Build abbreviated window key from round and window components.

    Usage:
        build_window_abbrev('1A', 2) -> 'R1AW2'
        build_window_abbrev('1F', 4) -> 'R1FW4'
        build_window_abbrev('2', 1)  -> 'R2W1'
    """
    return f"R{round_str}W{window_num}"


def dash_format_to_display_format(dash: str) -> str:
    """
    Convert dash format (e.g., '2026-27_T1') to BOSS display format
    (e.g., '2026-27 Term 1').

    Usage:
        dash_format_to_display_format('2026-27_T3A') -> '2026-27 Term 3A'
    """
    year_part, term_part = dash.split('_')
    full_term_name = TERM_DISPLAY_MAP.get(term_part, term_part)
    return f"{year_part} {full_term_name}"


def strip_term_prefix(term: str) -> str:
    """
    Strip leading 'T' from term codes.

    Usage:
        strip_term_prefix('T3A') -> '3A'
        strip_term_prefix('T1')  -> '1'
        strip_term_prefix('3A')  -> '3A'  (no-op if no T prefix)
    """
    if term.startswith('T'):
        return term[1:]
    return term


def encode_subterm_for_boss_id(term_code: str) -> str:
    """
    Encode sub-term suffix for BOSS ID construction.
    SMU term structure: T1, T2, T3A, T3B
    Mapping: A -> '1', B -> '2', no suffix -> '0'

    Usage:
        encode_subterm_for_boss_id('3A') -> '1'
        encode_subterm_for_boss_id('3B') -> '2'
        encode_subterm_for_boss_id('1')  -> '0'
    """
    if term_code.endswith('A'):
        return '1'
    elif term_code.endswith('B'):
        return '2'
    return '0'


# Lazy evaluation cache for expensive/time-dependent config values
_config_cache: Dict[str, object] = {}


def _compute_and_cache_window_names() -> None:
    """Compute CURRENT_WINDOW_NAME and PREVIOUS_WINDOW_NAME lazily on first access."""

    def _clean_window_name(entry):
        """Extract clean window name from schedule entry (e.g. 'Round 1A Window 1').

        Uses the abbrev field to produce consistent formatting without BOSS prefix.
        Falls back to raw entry[1] for legacy entries that lack an abbrev.
        """
        if len(entry) >= 3 and entry[2]:
            return abbrev_window_to_full(entry[2])
        return entry[1]  # legacy fallback

    target_current = os.getenv('TARGET_CURRENT_WINDOW')
    target_previous = os.getenv('TARGET_PREVIOUS_WINDOW')
    
    if target_current is not None or target_previous is not None:
        def _parse_target(val):
            if val is None: return None
            if val.lower() == 'none' or val.strip() == '': return None
            return val

        current = _parse_target(target_current)
        previous = _parse_target(target_previous)

        # Fallback: if CURRENT was provided but PREVIOUS wasn't (old schedules
        # that predate the Lambda passing TARGET_PREVIOUS_WINDOW), derive
        # PREVIOUS from bidding_schedules.json by finding the entry before CURRENT.
        if current is not None and previous is None:
            schedule = BIDDING_SCHEDULES.get(START_AY_TERM, [])
            for i, entry in enumerate(schedule):
                if _clean_window_name(entry) == current and i > 0:
                    previous = _clean_window_name(schedule[i - 1])
                    break

        _config_cache['CURRENT_WINDOW_NAME'] = current
        _config_cache['PREVIOUS_WINDOW_NAME'] = previous
        return

    schedule = BIDDING_SCHEDULES.get(START_AY_TERM, [])
    now = datetime.now()

    current_window_name = None
    previous_window_name = None

    for i, entry in enumerate(schedule):
        if now < entry[0]:
            current_window_name = _clean_window_name(entry)
            if i > 0:
                previous_window_name = _clean_window_name(schedule[i - 1])
            break

    if current_window_name is None and schedule:
        current_window_name = None
        previous_window_name = _clean_window_name(schedule[-1])

    _config_cache['CURRENT_WINDOW_NAME'] = current_window_name
    _config_cache['PREVIOUS_WINDOW_NAME'] = previous_window_name


def __getattr__(name):
    """Lazy evaluation for time-dependent and I/O-dependent config values."""
    if name == 'CURRENT_WINDOW_NAME':
        if name not in _config_cache:
            _compute_and_cache_window_names()
        return _config_cache[name]
    if name == 'PREVIOUS_WINDOW_NAME':
        if name not in _config_cache:
            _compute_and_cache_window_names()
        return _config_cache[name]
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")


def _reset_config_cache() -> None:
    """Clear cached config values. For testing only."""
    _config_cache.clear()


# ============================================================================
# PIPELINE CONFIGURATION
# ============================================================================

class PipelineConfig:
    """Configuration for PipelineCoordinator."""

    def __init__(
        self,
        bidding_schedules: dict,
        start_ay_term: str,
        db_config: dict,
        input_file: str = 'script_input/raw_data.xlsx',
        output_base: str = 'script_output',
        verify_dir: str = 'script_output/verify',
        cache_dir: str = 'db_cache',
        overall_results_dir: str = 'script_input/overallBossResults',
        use_supabase_storage: bool = False,
        supabase_url: Optional[str] = None,
        supabase_service_key: Optional[str] = None,
    ):
        self.bidding_schedules = bidding_schedules
        self.start_ay_term = start_ay_term
        self.db_config = db_config
        self.input_file = input_file
        self.output_base = output_base
        self.verify_dir = verify_dir
        self.cache_dir = cache_dir
        self.overall_results_dir = overall_results_dir
        self.use_supabase_storage = use_supabase_storage
        self.supabase_url = supabase_url
        self.supabase_service_key = supabase_service_key

    @classmethod
    def from_env(cls, bidding_schedules: dict, start_ay_term: str, db_config: dict):
        return cls(
            bidding_schedules=bidding_schedules,
            start_ay_term=start_ay_term,
            db_config=db_config,
            use_supabase_storage=USE_SUPABASE_STORAGE,
            supabase_url=SUPABASE_URL,
            supabase_service_key=SUPABASE_SERVICE_KEY,
        )


# ============================================================================
# BIDDING WINDOW PARSING
# ============================================================================

class _BiddingWindowFormat:
    """A single bidding window parsing format with regex pattern and mapper."""

    def __init__(self, pattern: str, mapper: Callable[[Any], Tuple[str, int]]):
        self._pattern = re.compile(pattern, re.IGNORECASE)
        self._mapper = mapper

    def try_parse(self, text: str) -> Optional[Tuple[str, int]]:
        m = self._pattern.search(text)
        return self._mapper(m) if m else None


_FORMATS: List[_BiddingWindowFormat] = [
    _BiddingWindowFormat(
        r'Incoming\s+Freshmen\s+(?:Rnd|Round)\s+(\w+)\s+(?:Win|Window)\s+(\d+)',
        lambda m: ("1F" if m.group(1) == "1" else f"{m.group(1)}F", int(m.group(2))),
    ),
    _BiddingWindowFormat(
        r'Incoming\s+Exchange\s+(?:Rnd|Round)\s+(\w+)\s+(?:Win|Window)\s+(\d+)',
        lambda m: (m.group(1), int(m.group(2))),
    ),
    _BiddingWindowFormat(
        r'Round\s+(\d[A-C]?|\d+F?)\s+Window\s+(\d+)',
        lambda m: (m.group(1), int(m.group(2))),
    ),
]
_FORMATS_WITH_ABBREV = _FORMATS + [
    _BiddingWindowFormat(
        r'Rnd\s+(\d[A-C]?|\d+F?)\s+Win\s+(\d+)',
        lambda m: (m.group(1), int(m.group(2))),
    ),
    _BiddingWindowFormat(
        r'^R(\d+[A-CF]?)W(\d+)$',
        lambda m: (m.group(1), int(m.group(2))),
    ),
]


def parse_bidding_window(
    bidding_window_str: str,
    *,
    allow_abbrev: bool = True,
    allow_generic_fallback: bool = False,
    default_round: Optional[str] = None,
    default_window: Optional[int] = None,
) -> Tuple[Optional[str], Optional[int]]:
    """
    Parse bidding window text into (round, window).

    Supported formats include:
    - Round 1 Window 1
    - Round 1A Window 2
    - Incoming Exchange Rnd 1C Win 1
    - Incoming Freshmen Rnd 1 Win 4
    - Rnd 1A Win 2
    """
    if bidding_window_str is None or (isinstance(bidding_window_str, float) and bidding_window_str != bidding_window_str):
        return default_round, default_window

    window_str = str(bidding_window_str).strip()
    if not window_str:
        return default_round, default_window

    for fmt in (_FORMATS_WITH_ABBREV if allow_abbrev else _FORMATS):
        result = fmt.try_parse(window_str)
        if result:
            return result

    if allow_generic_fallback:
        fallback_round_match = re.search(r'(\d[A-C]?|\d+F?)', window_str)
        if fallback_round_match:
            fallback_window_match = re.search(r'Window\s+(\d+)|Win\s+(\d+)', window_str, re.IGNORECASE)
            if fallback_window_match:
                window_num = int(fallback_window_match.group(1) or fallback_window_match.group(2))
                return fallback_round_match.group(1), window_num
            return fallback_round_match.group(1), 1

    return default_round, default_window